apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: simple-api
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      service: simple-api
  template:
    metadata:
      labels:
        service: simple-api
    spec:
      containers:
      - image: metanitesh/simple-api
        name: simple-api
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 3000
      restartPolicy: Always