- name: Deploy kubernetes
  hosts: server
  gather_facts: True
  become: true
  tasks:
  - git:
      repo: https://github.com/metanitesh/metanitesh-CI.CD.Jenkins.Ansible.Docker.K8s.git
      dest: /home/ubuntu/repo
      version: green-deployment
  
  - name: apply deployments
    shell:  kubectl apply -f /home/ubuntu/repo/k8s/deployment.yml

  - name: apply service
    shell:  kubectl apply -f /home/ubuntu/repo/k8s/service.yml

  - name: wait for pods to up
    wait_for: 
      delay: 60 
      timeout: 0 

  - name: port-forward
    shell: kubectl port-forward --address 0.0.0.0 service/simple-api 3000:3000
    async: 2592000
    poll: 0
    